CREATE DATABASE monezy;

\c monezy;

CREATE TABLE "Users" (
	"IdUser" INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	"NameUser" VARCHAR(30) NOT NULL,
	"SurnameUser" VARCHAR(50),
	CONSTRAINT "PK_User" PRIMARY KEY ("IdUser")
);

CREATE TABLE "Expenses" (
	"IdExpense" INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	"NameExpense" VARCHAR(20) NOT NULL,
	"DescriptionExpense" VARCHAR(50),
	"ValueExpense" FLOAT NOT NULL,
	"TypeExpense" INT NOT NULL,
	"CreatedExpense" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	"DateExpense" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	"UserId" INT NOT NULL,
	CONSTRAINT "PK_Expenses" PRIMARY KEY ("IdExpense"),
	CONSTRAINT "FK_Expenses" FOREIGN KEY ("UserId") REFERENCES "Users" ("IdUser")
);

